CREATE TABLE [dbo].[INSCRITO]
(
	[Id] INT NOT NULL PRIMARY KEY, 
    [Id_Alumno] INT NOT NULL, 
    [Cod] INT NOT NULL, 
    CONSTRAINT [FK_INSCRITO_ALUMNO] FOREIGN KEY ([Id_Alumno]) REFERENCES [ALUMNO]([id]), 
    CONSTRAINT [FK_INSCRITO_CURSO] FOREIGN KEY ([Cod]) REFERENCES [CURSO]([Cod])
)
